update zshrc file

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,171 +1,141 @@
-# Get right system
-
-OS="$(uname -s)"
+# Determine the operating system
+OS=$(uname -s)
 case "$OS" in
   Linux*)
     if [ -f /etc/arch-release ]; then
-	CONFIG="arch"
-    elif [ -f /etc/lsb-release ] && grep -qi "ubuntu" /etc/lsb-release; then
-	CONFIG="wsl"
-    else
-      echo "Unsupported Linux distro"
-      exit 1
+      CONFIG="arch"
+    elif grep -qi "ubuntu" /etc/lsb-release 2>/dev/null; then
+      CONFIG="wsl"
     fi
-      ;;
-    Darwin*)
-	CONFIG="mac"
-      ;;
-    *)
-      echo "Unsupported Linux distro"
-      exit 1
-      ;;
-  esac
+    ;;
+  Darwin*)
+    CONFIG="mac"
+    ;;
+  *)
+    ;;
+esac
 
-# Configuration for Linux
-if [[ "$CONFIG" == 'arch' ]]; then
-    #Display Pokemon
-    pokemon-colorscripts --no-title -r 1,3,6
+# Linux-specific configuration
+if [[ "$CONFIG" == "arch" ]]; then
+  # Display Pokémon
+  pokemon-colorscripts --no-title -r 1,3,6
 
-    # Helpful aliases
-    alias  c='clear' # clear terminal
-    alias  l='eza -lh  --icons=auto' # long list
-    alias ls='eza -1   --icons=auto' # short list
-    alias ll='eza -lha --icons=auto --sort=name --group-directories-first' # long list all
-    alias ld='eza -lhD --icons=auto' # long list dirs
-    alias lt='eza --icons=auto --tree' # list folder as tree
-    alias un='$aurhelper -Rns' # uninstall package
-    alias up='$aurhelper -Syu' # update system/package/aur
-    alias pl='$aurhelper -Qs' # list installed package
-    alias pa='$aurhelper -Ss' # list availabe package
-    alias pc='$aurhelper -Sc' # remove unused cache
-    alias po='$aurhelper -Qtdq | $aurhelper -Rns -' # remove unused packages, also try > $aurhelper -Qqd | $aurhelper -Rsu --print -
-    alias github='cd ~/github'
+  # Detect the AUR helper
+  aurhelper=""
+  if pacman -Qi yay &>/dev/null; then
+    aurhelper="yay"
+  elif pacman -Qi paru &>/dev/null; then
+    aurhelper="paru"
+  fi
 
-    # Detect the AUR wrapper
-    if pacman -Qi yay &>/dev/null ; then
-        aurhelper="yay"
-        elif pacman -Qi paru &>/dev/null ; then
-        aurhelper="paru"
+  # Helper function for installing packages
+  in() {
+    local arch_pkgs=() aur_pkgs=()
+    for pkg in "$@"; do
+      if pacman -Si "$pkg" &>/dev/null; then
+        arch_pkgs+=("$pkg")
+      else
+        aur_pkgs+=("$pkg")
+      fi
+    done
+    [[ ${#arch_pkgs[@]} -gt 0 ]] && sudo pacman -S "${arch_pkgs[@]}"
+    [[ ${#aur_pkgs[@]} -gt 0 ]] && $aurhelper -S "${aur_pkgs[@]}"
+  }
+
+  # Command not found handler
+  command_not_found_handler() {
+    local purple='\e[1;35m' bright='\e[0;1m' green='\e[1;32m' reset='\e[0m'
+    printf 'zsh: command not found: %s\n' "$1"
+    local entries=($(pacman -F --machinereadable -- "/usr/bin/$1"))
+    if [[ ${#entries[@]} -gt 0 ]]; then
+      echo "${bright}$1${reset} may be found in the following packages:"
+      local pkg=""
+      for entry in "${entries[@]}"; do
+        local fields=(${(z)entry})
+        if [[ "$pkg" != "${fields[2]}" ]]; then
+          printf "${purple}%s/${bright}%s ${green}%s${reset}\n" "${fields[1]}" "${fields[2]}" "${fields[3]}"
+        fi
+        echo "    /${fields[4]}"
+        pkg="${fields[2]}"
+      done
     fi
+    return 127
+  }
 
-    function in {
-        local -a inPkg=("$@")
-        local -a arch=()
-        local -a aur=()
-
-        for pkg in "${inPkg[@]}"; do
-            if pacman -Si "${pkg}" &>/dev/null ; then
-                arch+=("${pkg}")
-            else
-                aur+=("${pkg}")
-            fi
-        done
-
-        if [[ ${#arch[@]} -gt 0 ]]; then
-            sudo pacman -S "${arch[@]}"
-        fi
-
-        if [[ ${#aur[@]} -gt 0 ]]; then
-            ${aurhelper} -S "${aur[@]}"
-        fi
-    }
-
-    # In case a command is not found, try to find the package that has it
-    function command_not_found_handler {
-        local purple='\e[1;35m' bright='\e[0;1m' green='\e[1;32m' reset='\e[0m'
-        printf 'zsh: command not found: %s\n' "$1"
-        local entries=( ${(f)"$(/usr/bin/pacman -F --machinereadable -- "/usr/bin/$1")"} )
-        if (( ${#entries[@]} )) ; then
-            printf "${bright}$1${reset} may be found in the following packages:\n"
-            local pkg
-            for entry in "${entries[@]}" ; do
-                local fields=( ${(0)entry} )
-                if [[ "$pkg" != "${fields[2]}" ]] ; then
-                    printf "${purple}%s/${bright}%s ${green}%s${reset}\n" "${fields[1]}" "${fields[2]}" "${fields[3]}"
-                fi
-                printf '    /%s\n' "${fields[4]}"
-                pkg="${fields[2]}"
-            done
-        fi
-        return 127
-    }
+  # Arch-specific aliases
+  alias c='clear'
+  alias l='eza -lh --icons=auto'
+  alias ls='eza -1 --icons=auto'
+  alias ll='eza -lha --icons=auto --sort=name --group-directories-first'
+  alias ld='eza -lhD --icons=auto'
+  alias lt='eza --icons=auto --tree'
+  alias un='$aurhelper -Rns'
+  alias up='$aurhelper -Syu'
+  alias pl='$aurhelper -Qs'
+  alias pa='$aurhelper -Ss'
+  alias pc='$aurhelper -Sc'
+  alias po='$aurhelper -Qtdq | $aurhelper -Rns -'
+  alias github='cd ~/github'
 fi
 
-# MacOS config
-if [[ "$CONFIG" == 'mac' ]]; then
-	alias github='cd ~/Document/GitHub'
+# macOS-specific configuration
+if [[ "$CONFIG" == "mac" ]]; then
+  alias github='cd ~/Documents/GitHub'
 fi
 
-# MacOS config
-if [[ "$CONFIG" == 'wsl' ]]; then
-	# Add HOMEBREW to path
-	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+# WSL-specific configuration
+if [[ "$CONFIG" == "wsl" ]]; then
+  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
 fi
 
-# Initialization code that may require console input (password prompts, [y/n]
-# confirmations, etc.) must go above this block; everything else may go below.
-if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
-  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
-fi
+# Make nvim default editor
+export EDITOR="nvim"
+export VISUAL="nvim"
 
-# Path to your oh-my-zsh installation.
-# ZSH=$HOME/oh-my-zsh/
+# Oh-my-zsh setup
 ZSH="${HOME}/.oh-my-zsh"
-
-# Load oh-my-zsh
 source $ZSH/oh-my-zsh.sh
-
-# Load oh-my-zsh theme
 source ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
 
-
-# List of plugins used
-plugins=( git sudo zsh-256color zsh-interactive-cd )
-
-#ZSH-AUTOSUGGESTIONS
-bindkey 'jq' autosuggest-accept
-bindkey 'jj' autosuggest-execute
-ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=("forward-char" "vi-forward-char")
-ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg-cyan'
-export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg-cyan'
+# Plugin setup
+plugins=(git sudo zsh-256color zsh-interactive-cd)
 source $ZSH/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
 source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 
-# change ls to use eza
-alias ls='eza --color=always --icons=always --long --git --no-filesize --no-user --no-permissions'
+# Autosuggestions configuration
+bindkey 'jk' autosuggest-accept
+bindkey 'jj' autosuggest-execute
+export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg-cyan'
 
-# Handy change dir shortcuts
+# Custom aliases
+alias ls='eza --color=always --icons=always --long --git --no-filesize --no-user --no-permissions'
 alias ..='cd ..'
 alias ...='cd ../..'
 alias .3='cd ../../..'
 alias .4='cd ../../../..'
 alias .5='cd ../../../../..'
-
-# custom alias
 alias fzfc='code $(fzf --preview="bat --color=always {}")'
 alias sz='source ~/.zshrc'
-alias ez='code ~/.zshrc'
-
-# custom commands
-
-cheat() {
-    curl cheat.sh/$1
-}
-
-# Define the resudo function to rerun the last command with sudo
-redo() {
-    # Get the last command from the history
-    last_command=$(fc -ln -1)
-
-    # Execute the last command with sudo
-    sudo $last_command
-}
-
-# Always mkdir a path (this doesn't inhibit functionality to make a single dir)
+alias ez='nvim ~/.zshrc'
 alias mkdir='mkdir -p'
+alias nv='nvim'
+alias vim='nvim'
+if ! command -v zoxide &> /dev/null; then
+  alias cd='z'
+fi
 
-source <(fzf --zsh)
 
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+# Custom commands
+cheat() {
+  curl cheat.sh/$1
+}
+
+redo() {
+  sudo $(fc -ln -1)
+}
+
+# Load p10k configuration if available
+[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && \
+  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
+[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
 
